### ISSUE TITLE
Vorbereitung Konsultation - Fragen

### ISSUE THREAD

**Issue by b4ghir1** [MxHbm/Management-Science#32]
- [ ] #35  -> Constraint 1.9 führt zu Infeasible-Fehlermeldung. 
- [ ] #28 -> Parameter i0_f,l ist definiert. i0_f,FW ist nicht definiert. (Ergänzen wir hier lediglich die fehlende Parameterdefinition und iterieren über FW anstelle von L? Obwohl man an der Stelle auch anmerken kann, dass FW das Set aller Factory Warehouse's  ist und man an der Stelle nicht wie sonst üblich über das i-te (oder l-te) Element aus dem Set I (oder L) auswählt.
- [ ] zur Abkürzung FW: meiner Meinung nach it FW nicht explizit als Factory Warehouse im Paper benannt
- [ ] #27 -> entweder wurden die falschen Sets als Indices genutzt oder es fehlen Indices im Paper.
- [ ] #21 -> Parameter Rho_s: Hier sind wir mittlerweile so weit, dass wir hier nur die 9 reduzierten Szenarios in der Laufvariable s in S übergeben werden. Gleichzeitig muss für die Umsetzung mit Gurobi hier über s iteriert werden und wenn man die Gleichung (52) exakt so umsetzen möchte wie im Paper, kann man nicht über Rho_s iterieren. Somit muss Rho_s für die Umsetzung mit Gurobi in die bestehende Summe als Faktor mit rein gezogen werden.
- [ ] #10 --> Epsilon wird in Tabelle 2 als Integer definiert. später im Paper (Case Study) wird Epsilon mit 0.0001 definiert und hat somit keine Auswirkung mehr auf den Scenario Reduction Algorithm. Das kann natürlich so gewollt sein, aber gefühlt ist dieser Widerspruch nicht wirklich gewollt.
- [ ] #6 --> Wie behandeln wir Parameter für die keine Werte im Paper gegeben sind? Erzeugen wir einfach irgendwelche - allerdings lässt sich dann das Ergebnis im Paper nicht mehr so nachvollziehen.

edit:
- #35 ergänzt.

**Comment by MxHbm** [comment]
Konsultation war erfolgreich!
